Permissions Size User  Date Modified Name
drwxr-xr-x     - mouad  5 Nov 19:26  .git
.rw-r--r--   357 mouad  4 Nov 20:51  .gitignore
.rw-r--r--  2.6k mouad  5 Nov 19:33  main.cpp
.rw-r--r--   52k mouad  5 Nov 19:34  main.o
.rw-r--r--   352 mouad  4 Nov 20:50  Makefile
.rw-r--r--     0 mouad  5 Nov 19:34  nginx.conf
.rw-r--r--    11 mouad  3 Nov 19:03  README.md
.rw-r--r--   104 mouad  4 Nov 21:00  todo.txt
.rwxr-xr-x   46k mouad  5 Nov 19:34  webserv
Permissions Size User  Date Modified Name
drwxr-xr-x     - mouad  5 Nov 19:26  .git
.rw-r--r--   357 mouad  4 Nov 20:51  .gitignore
.rw-r--r--  2.6k mouad  5 Nov 19:33  main.cpp
.rw-r--r--   52k mouad  5 Nov 19:34  main.o
.rw-r--r--   352 mouad  4 Nov 20:50  Makefile
.rw-r--r--   454 mouad  5 Nov 19:34  nginx.conf
.rw-r--r--    11 mouad  3 Nov 19:03  README.md
.rw-r--r--   104 mouad  4 Nov 21:00  todo.txt
.rwxr-xr-x   46k mouad  5 Nov 19:34  webserv
Permissions Size User  Date Modified Name
drwxr-xr-x     - mouad  5 Nov 19:26  .git
.rw-r--r--   357 mouad  4 Nov 20:51  .gitignore
.rw-r--r--  2.6k mouad  5 Nov 19:33  main.cpp
.rw-r--r--   52k mouad  5 Nov 19:34  main.o
.rw-r--r--   352 mouad  4 Nov 20:50  Makefile
.rw-r--r--   908 mouad  5 Nov 19:34  nginx.conf
.rw-r--r--    11 mouad  3 Nov 19:03  README.md
.rw-r--r--   104 mouad  4 Nov 21:00  todo.txt
.rwxr-xr-x   46k mouad  5 Nov 19:34  webserv
