server {
    listen 8085;
    host 127.0.0.1;
    server_name sandbox;
    root ./www;
    index index.html;
    client_max_body_size 1G;
    autoindex on;
    error_page 404 /errors/404.html;
    error_page 401 /errors/401.html;
    error_page 500 /errors/500.html;

    location / {
        allow_methods GET POST;
        return ./documentation/index.html;
    }

    location /upload {
        root ./www;
        allow_methods POST GET DELETE;
        client_max_body_size 2G;
        autoindex on;
    }

    location /cgi-bin {
        root ./www;
        cgi_ext .py .sh .pl .rb .php;
        cgi_path /usr/bin/python3 /bin/bash /usr/bin/perl /usr/bin/ruby /usr/bin/php;
        index handler.py;
        allow_methods GET POST DELETE;
    }
    location /dummy {
        return /index.html;
      }
    
    location /delete {
    root ./www;
    allow_methods DELETE;
    autoindex on;
    }
    
    location /documentation 
    {
      root ./www;
      allow_methods GET;
      index index.html;
    }
}
