server {
    listen 8085;
    host 127.0.0.1;
    server_name sandbox;
    root ./www;
    index index.html;
    client_max_body_size 1G;
    autoindex on;
    error_page 404 /errors/404.html;
    error_page 401 /errors/401.html;
    error_page 500 /errors/500.html;

    location / {
        allow_methods GET POST;
        # index index.html;
        autoindex on;
    }

    location /upload {
        root ./www;
        allow_methods POST GET;
        client_max_body_size 100M;
        autoindex on;
    }

    location /cgi-bin {
        root ./www;
        cgi_ext .py .sh .pl .rb;
        cgi_path /usr/bin/python3 /bin/bash /usr/bin/perl /home/mouad/.local/share/mise/installs/ruby/3.4.7/bin/ruby;
        index handler.py;
        allow_methods GET POST DELETE;
    }
    
    location /delete {
    root ./www;
    allow_methods DELETE;
    autoindex on;
    }
}
